import layout from './captureSheet.json'
import type { Point2D } from './geometry/homography'

/**
 * The printed capture sheet's geometry, in millimetres.
 *
 * `captureSheet.json` is generated by `scripts/make_marker_sheet.py` alongside
 * the PDF itself, so the app and the sheet can never disagree about where a
 * marker is: change the layout, rerun the script, and both move together.
 */
export interface CaptureSheetLayout {
  dictionary: string
  pageWidthMm: number
  pageHeightMm: number
  markerSizeMm: number
  /** Printed reflectance of the lens zone, 0-255. */
  zoneGrey: number
  controlRulerMm: { x0: number; y: number; x1: number }
  textureRectMm: { x0: number; y0: number; x1: number; y1: number }
  markers: Record<string, [number, number][]>
}

export const CAPTURE_SHEET = layout as unknown as CaptureSheetLayout

/** Marker id -> its 4 printed corners in sheet millimetres, same order as the
 * detector returns them. */
export const SHEET_MARKER_CORNERS_MM: Map<number, Point2D[]> = new Map(
  Object.entries(CAPTURE_SHEET.markers).map(([id, corners]) => [
    Number(id),
    corners.map(([x, y]) => ({ x, y })),
  ]),
)

/**
 * Nominal length of the sheet's printed control segment, in millimetres.
 *
 * Measuring it after printing is what makes the sheet work on any printer. Most
 * print dialogs default to "fit to page" and quietly scale the whole sheet by a
 * few percent — or, on a printer that cannot be talked out of its margins, by
 * sixteen. Every marker, and so every measurement, scales with it. Reading this
 * line with a caliper turns that from a silent error into one number.
 */
export const CONTROL_LENGTH_MM =
  CAPTURE_SHEET.controlRulerMm.x1 - CAPTURE_SHEET.controlRulerMm.x0

/** Where the lens is meant to sit. Anything the segmenter finds outside this
 * rectangle (plus a margin) is sheet furniture, not a lens. */
export const LENS_ZONE_MM = CAPTURE_SHEET.textureRectMm
